'use strict';
const stages=[
['EL MENSAJE','Una petición cotidiana.','La primera prueba parte de un cambio de cita ficticio.','Hola, soy Elena (personaje ficticio). Necesito cambiar mi cita del martes. Tengo disponibilidad por las tardes. ¿Podríamos buscar otro día? Gracias.','En el piloto se utiliza este ejemplo fijo. La lectura y selección de correos reales es un siguiente paso.'],
['LA PROPUESTA','La IA prepara un primer texto.','El modelo local redacta una respuesta a partir del mensaje y las instrucciones del negocio.','Querida Elena,\n\nEs un placer atender su solicitud. Agradezco que nos avise con antelación para ajustar nuestra agenda.\n\n¿Podría indicarme algunas tardes que le resulten convenientes para que podamos revisar la disponibilidad?','Fragmento de la respuesta real generada durante la prueba.'],
['TU REVISIÓN','Tú decides cómo suena.','La respuesta se presenta en un campo editable. Puedes revisar el tono, corregir errores y ajustar el contenido antes de guardarlo.','Revisar el saludo.\nComprobar que no se inventan horarios.\nAjustar el texto a la forma de hablar de la profesional.','En una primera generación aparecieron horarios inventados. Ajustamos las instrucciones y añadimos una comprobación limitada; la revisión humana sigue siendo necesaria.'],
['EL BORRADOR','Preparado en Gmail.','Al pulsar Guardar, Savia crea un borrador en la cuenta autorizada.','[DEMO SAVIA] Cambio de cita — respuesta de prueba\n\nEstado comprobado: borrador.\nDestinatarios: ninguno.\nEnviado: no.','Prueba completada el 24 de septiembre de 2026. Esta página de portfolio solo representa el resultado.']
];
function show(i){['stage-label','stage-title','stage-copy','stage-example','stage-note'].forEach((id,j)=>document.getElementById(id).textContent=stages[i][j]);document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.step)===i)));}
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.step))));show(0);
