const scenarios=[
 {name:'Crear una web',match:/web|pagina|página|sitio|cliente/,context:'Proyecto web · Del encargo a la entrega',reply:'He dividido el proyecto en pasos revisables. Empezaría aclarando el alcance con el cliente.',tasks:['Definir objetivos, público y alcance','Preparar estructura y diseño para revisión','Construir las páginas acordadas','Revisar contenidos, móvil y accesibilidad','Comprobar privacidad, formularios y cookies','Publicar y documentar la entrega']},
 {name:'Organizar la semana',match:/semana|pendiente|organizar|trabajo/,context:'Semana de trabajo · Prioridades',reply:'Vamos a sacar las tareas de la cabeza y poner primero lo que tiene plazo.',tasks:['Anotar todo lo pendiente','Identificar fechas límite y tareas urgentes','Elegir tres prioridades para empezar','Reservar tiempo para trabajo concentrado','Revisar avances y reajustar al final del día']},
 {name:'Seguir correos',match:/correo|email|proveedor|factura/,context:'Correo · Seguimiento sin olvidos',reply:'Te propongo un recorrido para que cada mensaje tenga un siguiente paso claro.',tasks:['Revisar los mensajes que necesitan respuesta','Separar los que esperan datos de otra persona','Preparar borradores para revisión','Anotar a quién hay que volver a escribir','Comprobar los pendientes antes de cerrar el día']}
];const $=id=>document.getElementById(id);let tasks=[];let id=0;
function bubble(text,who){const p=document.createElement('p');p.className='bubble '+who;p.textContent=text;$('messages').append(p);$('messages').scrollTop=$('messages').scrollHeight}
function render(){const list=$('tasks');list.replaceChildren();tasks.forEach(t=>{const li=document.createElement('li');if(t.done)li.classList.add('done');const input=document.createElement('input');input.type='checkbox';input.id='task-'+t.id;input.checked=t.done;input.addEventListener('change',()=>{t.done=input.checked;render()});const label=document.createElement('label');label.htmlFor=input.id;label.textContent=t.title;li.append(input,label);list.append(li)});const done=tasks.filter(t=>t.done).length;$('progress').textContent=done+' de '+tasks.length;$('avatar-status').textContent=tasks.length?(done===tasks.length?'Todo revisado':'Organizando contigo'):'Listo para organizar'}
function scenario(s,text){bubble(text||s.name,'user');bubble(s.reply,'bot');$('context').textContent=s.context;tasks=s.tasks.map(title=>({id:++id,title,done:false}));$('status').textContent='Plan preparado';render()}
scenarios.forEach(s=>{const b=document.createElement('button');b.textContent=s.name;b.type='button';b.addEventListener('click',()=>scenario(s));$('prompts').append(b)});
$('chat-form').addEventListener('submit',e=>{e.preventDefault();const v=$('message').value.trim();if(!v)return;$('message').value='';const s=scenarios.find(s=>s.match.test(v));if(s)scenario(s,v);else{bubble(v,'user');bubble('Puedo enseñarte tres ejemplos: crear una web, organizar una semana o seguir correos. Elige uno para ver un plan. Esta demo todavía no interpreta cualquier solicitud libre.','bot')}});
$('add-form').addEventListener('submit',e=>{e.preventDefault();const title=$('new-task').value.trim();if(!title)return;tasks.push({id:++id,title,done:false});$('new-task').value='';$('context').textContent=tasks.length===1?'Tu lista de tareas':'Plan con una tarea añadida';render()});
$('reset').addEventListener('click',()=>{tasks=[];$('context').textContent='Elige un ejemplo para ver cómo se ordenan sus pasos.';$('status').textContent='Esperando tu idea';$('messages').replaceChildren();bubble('Hola, soy Smerald. ¿Qué quieres organizar hoy?','bot');render()});render();
