const scenarios=[
 {name:'Crear una web',match:/web|pagina|página|sitio|cliente/,context:'Proyecto web · Del encargo a la entrega',reply:'Una web tiene muchas piezas, sí. Vamos a ponerles orden. Empezaría hablando del alcance con el cliente; después ya habrá tiempo de diseñar y construir.',tasks:['Definir objetivos, público y alcance','Preparar estructura y diseño para revisión','Construir las páginas acordadas','Revisar contenidos, móvil y accesibilidad','Comprobar privacidad, formularios y cookies','Publicar y documentar la entrega']},
 {name:'Organizar la semana',match:/semana|pendiente|organizar|trabajo/,context:'Semana de trabajo · Prioridades',reply:'Respira, que no hace falta resolverlo todo a la vez. Saquemos los pendientes de la cabeza y elijamos tres prioridades para empezar.',tasks:['Anotar todo lo pendiente','Identificar fechas límite y tareas urgentes','Elegir tres prioridades para empezar','Reservar tiempo para trabajo concentrado','Revisar avances y reajustar al final del día']},
 {name:'Seguir correos',match:/correo|email|proveedor|factura/,context:'Correo · Seguimiento sin olvidos',reply:'Esos correos abiertos ocupan espacio en la cabeza. Vamos a dar a cada uno un siguiente paso y dejar claro qué queda en espera.',tasks:['Revisar los mensajes que necesitan respuesta','Separar los que esperan datos de otra persona','Preparar borradores para revisión','Anotar a quién hay que volver a escribir','Comprobar los pendientes antes de cerrar el día']}
];const $=id=>document.getElementById(id);let tasks=[];let id=0;
function bubble(text,who){const p=document.createElement('p');p.className='bubble '+who;p.textContent=text;$('messages').append(p);$('messages').scrollTop=$('messages').scrollHeight}
function render(){const todo=$('todo-tasks');const complete=$('done-tasks');todo.replaceChildren();complete.replaceChildren();tasks.forEach(t=>{const li=document.createElement('li');if(t.done)li.classList.add('done');const input=document.createElement('input');input.type='checkbox';input.id='task-'+t.id;input.checked=t.done;input.addEventListener('change',()=>{t.done=input.checked;render();if(t.done)bubble(tasks.every(item=>item.done)?'¡Plan completado! Mira todo lo que has avanzado. ✦':'Bien hecho. Un paso terminado; seguimos cuando quieras.','bot')});const label=document.createElement('label');label.htmlFor=input.id;label.textContent=t.title;li.append(input,label);(t.done?complete:todo).append(li)});const done=tasks.filter(t=>t.done).length;$('progress').textContent=done+' de '+tasks.length;$('avatar-status').textContent=tasks.length?(done===tasks.length?'Todo revisado':'Organizando contigo'):'Listo para organizar'}
function scenario(s,text){bubble(text||s.name,'user');bubble(s.reply,'bot');$('context').textContent=s.context;tasks=s.tasks.map(title=>({id:++id,title,done:false}));$('status').textContent='Plan preparado';render()}
scenarios.forEach(s=>{const b=document.createElement('button');b.textContent=s.name;b.type='button';b.addEventListener('click',()=>scenario(s));$('prompts').append(b)});
$('chat-form').addEventListener('submit',e=>{e.preventDefault();const v=$('message').value.trim();if(!v)return;$('message').value='';const s=scenarios.find(s=>s.match.test(v));if(s)scenario(s,v);else{bubble(v,'user');bubble(/agobi|abruma|bloque|no sé|no se|ansiedad/.test(v.toLowerCase())?'Vamos con calma. No hace falta hacerlo todo hoy. Elige un ejemplo y encontraremos una primera tarea pequeña para empezar.':'Me gusta que me lo cuentes. En esta demo puedo ayudarte con tres ejemplos: crear una web, organizar una semana o seguir correos. Elige uno y lo ordenamos juntas.','bot')}});
$('add-form').addEventListener('submit',e=>{e.preventDefault();const title=$('new-task').value.trim();if(!title)return;tasks.push({id:++id,title,done:false});$('new-task').value='';bubble('Anotado. Una cosa menos dando vueltas en la cabeza.','bot');$('context').textContent=tasks.length===1?'Tu lista de tareas':'Plan con una tarea añadida';render()});
$('next-step').addEventListener('click',()=>{const next=tasks.find(t=>!t.done);if(!tasks.length){bubble('Elige un ejemplo o añade una tarea, y te ayudo a decidir por dónde empezar.','bot');return}if(!next){bubble('¡Has completado todo el plan! Date un momento para reconocerlo. ✦','bot');return}bubble('Yo empezaría por: «'+next.title+'». Puedes dedicarle solo diez minutos. Después vemos el siguiente paso.','bot');document.getElementById('task-'+next.id)?.focus()});
$('reset').addEventListener('click',()=>{tasks=[];$('context').textContent='Elige un ejemplo para ver cómo se ordenan sus pasos.';$('status').textContent='Esperando tu idea';$('messages').replaceChildren();bubble('Empezamos de nuevo. ¿Qué te apetece poner en orden hoy?','bot');render()});render();
