const config={
 citas:{name:'Brisa',cases:[
 {title:'Primera cita',from:'Persona interesada',incoming:'Hola, me gustaría pedir una primera cita. ¿Tenéis disponibilidad la semana que viene?',draft:'Hola:\n\nGracias por escribirnos. Podemos revisar la disponibilidad de la próxima semana. ¿Qué días y horarios te vienen mejor?\n\nUn saludo.',answer:'Perfecto, vamos con calma. He preparado una respuesta que pregunta por la disponibilidad sin prometer un horario que aún no conocemos.'},
 {title:'Cambiar horario',from:'Persona con cita',incoming:'Hola, necesito cambiar la cita del jueves por la tarde. ¿Podemos buscar otra fecha?',draft:'Hola:\n\nGracias por avisar. Revisaremos otras fechas disponibles. ¿Puedes indicarnos qué horarios te vendrían bien?\n\nUn saludo.',answer:'No pasa nada, los planes cambian. Te dejo una respuesta amable para buscar otra opción antes de mover la agenda.'},
 {title:'Videollamada',from:'Persona interesada',incoming:'Buenas, ¿ofrecéis sesiones por videollamada? Querría conocer las opciones.',draft:'Hola:\n\nGracias por tu consulta. Podemos informarte sobre las modalidades disponibles y cómo solicitar una cita. ¿Quieres que te enviemos más detalles?\n\nUn saludo.',answer:'Buena pregunta. Te propongo un borrador claro y dejamos la confirmación para cuando revises las opciones disponibles.'}]},
 correo:{name:'Ámbar',cases:[
 {title:'Factura recibida',from:'Proveedor de ejemplo',incoming:'Buenos días, os adjuntamos la factura correspondiente a este mes. Un saludo.',draft:'Buenos días:\n\nHemos recibido la factura. Gracias por enviarla.\n\nUn saludo.',answer:'Una menos pendiente. Te dejo un acuse breve para que decidas si quieres enviarlo.'},
 {title:'Falta una factura',from:'Administración',incoming:'Hola, revisando la documentación vemos que falta la factura de agosto. ¿Podéis solicitarla?',draft:'Buenos días:\n\nEstamos revisando nuestra documentación y nos falta la factura de agosto. ¿Podéis enviárnosla, por favor?\n\nMuchas gracias.',answer:'Vamos a pedirla con claridad. He dejado un borrador; añade el número o la referencia antes de usarlo.'},
 {title:'Pedir al proveedor',from:'Equipo interno',incoming:'Necesitamos que el proveedor nos confirme cuándo podrá entregar el material solicitado.',draft:'Buenos días:\n\n¿Podéis confirmarnos la fecha prevista de entrega del material solicitado? Quedamos pendientes de vuestra respuesta.\n\nGracias y un saludo.',answer:'Te preparo el primer paso. Puedes añadir el material y el número de pedido para que el proveedor tenga todo el contexto.'}]}
};
const kind=document.body.dataset.demo;const data=config[kind];const $=id=>document.getElementById(id);const cases=$('cases');let active=-1;
function bubble(message,who){const p=document.createElement('p');p.className='bubble '+who;p.textContent=message;$('chat').append(p);$('chat').scrollTop=$('chat').scrollHeight}
function select(i,custom){active=i;const item=data.cases[i];bubble(custom||item.title,'user');$('pet-status').textContent='Organizando el caso…';$('draft-status').textContent='Preparando borrador';setTimeout(()=>{bubble(item.answer,'bot');$('sender').textContent=item.from;$('incoming').textContent=item.incoming;$('draft').value=item.draft;$('draft-status').textContent='Listo para revisar';$('pet-status').textContent='Borrador preparado';$('feedback').textContent='Puedes editar el texto antes de marcarlo como revisado.';cases.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)))},300)}
data.cases.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.textContent=item.title;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>select(i));cases.append(b)});
$('chat-form').addEventListener('submit',e=>{e.preventDefault();const v=$('message').value.trim();if(!v)return;$('message').value='';const t=v.toLowerCase();let i=kind==='citas'?(/cambi|mover|aplaz/.test(t)?1:/video|online|distancia/.test(t)?2:/cita|hora|disponib/.test(t)?0:-1):(/proveedor|material|entrega/.test(t)?2:/falta|pedir|solicit|reclam/.test(t)?1:/factura|recib/.test(t)?0:-1);if(i<0){bubble(v,'user');bubble(`Puedo mostrarte estos tres ejemplos: ${data.cases.map(x=>x.title).join(', ')}. Elige uno para ver cómo trabajaría; todavía no interpreto cualquier mensaje libre.`,'bot');return}select(i,v)});
$('approve').addEventListener('click',()=>{if(!$('draft').value.trim()){$('feedback').textContent='Primero elige un caso y prepara un borrador.';return}$('draft-status').textContent='Revisado en la demo';$('pet-status').textContent='Revisión terminada';$('feedback').textContent='Marcado como revisado. No se ha enviado ningún mensaje.';bubble('Borrador revisado. No he enviado ningún correo.','bot')});
$('reset').addEventListener('click',()=>{active=-1;$('sender').textContent='—';$('incoming').textContent='Selecciona un caso para ver el mensaje de ejemplo.';$('draft').value='';$('draft-status').textContent='Esperando un caso';$('pet-status').textContent='Esperando tu consulta';$('feedback').textContent='';$('chat').replaceChildren();bubble(`¡Hola! Soy ${data.name}. Elige un ejemplo y empezamos.`, 'bot');cases.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'))});

if(kind==='correo'){const dialog=$('chat-dialog');const panel=document.querySelector('.conversation-panel');const originalParent=panel.parentNode;const draftPanel=document.querySelector('.draft-panel');$('open-chat').addEventListener('click',()=>{dialog.querySelector('#chat-dialog-content').append(panel);dialog.showModal();$('message').focus()});const close=()=>{originalParent.insertBefore(panel,draftPanel.nextSibling);if(dialog.open)dialog.close()};$('close-chat').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('click',e=>{if(e.target===dialog)close()})}
