const config={
 citas:{cases:[
 {title:'Primera cita',from:'Persona interesada',incoming:'Hola, me gustaría pedir una primera cita. ¿Tenéis disponibilidad la semana que viene?',draft:'Hola:\n\nGracias por escribirnos. Podemos revisar la disponibilidad de la próxima semana. ¿Qué días y horarios te vienen mejor?\n\nUn saludo.'},
 {title:'Cambio de horario',from:'Persona con cita',incoming:'Hola, necesito cambiar la cita del jueves por la tarde. ¿Podemos buscar otra fecha?',draft:'Hola:\n\nGracias por avisar. Revisaremos otras fechas disponibles. ¿Puedes indicarnos qué horarios te vendrían bien?\n\nUn saludo.'},
 {title:'Consulta sobre modalidad',from:'Persona interesada',incoming:'Buenas, ¿ofrecéis sesiones por videollamada? Querría conocer las opciones.',draft:'Hola:\n\nGracias por tu consulta. Podemos informarte sobre las modalidades disponibles y cómo solicitar una cita. ¿Quieres que te enviemos más detalles?\n\nUn saludo.'}]},
 correo:{cases:[
 {title:'Factura recibida',from:'Proveedor de ejemplo',incoming:'Buenos días, os adjuntamos la factura correspondiente a este mes. Un saludo.',draft:'Buenos días:\n\nHemos recibido la factura. Gracias por enviarla.\n\nUn saludo.'},
 {title:'Falta una factura',from:'Administración',incoming:'Hola, revisando la documentación vemos que falta la factura de agosto. ¿Podéis solicitarla?',draft:'Buenos días:\n\nEstamos revisando nuestra documentación y nos falta la factura de agosto. ¿Podéis enviárnosla, por favor?\n\nMuchas gracias.'},
 {title:'Petición al proveedor',from:'Equipo interno',incoming:'Necesitamos que el proveedor nos confirme cuándo podrá entregar el material solicitado.',draft:'Buenos días:\n\n¿Podéis confirmarnos la fecha prevista de entrega del material solicitado? Quedamos pendientes de vuestra respuesta.\n\nGracias y un saludo.'}]}
};
const kind=document.body.dataset.demo;const cases=config[kind].cases;const list=document.querySelector('#cases');const sender=document.querySelector('#sender');const incoming=document.querySelector('#incoming');const draft=document.querySelector('#draft');const feedback=document.querySelector('#feedback');let selected=0;let prepared=false;
function render(){list.replaceChildren();cases.forEach((item,i)=>{const b=document.createElement('button');b.className='case';b.type='button';b.setAttribute('aria-pressed',String(i===selected));const title=document.createElement('strong');title.textContent=item.title;const sub=document.createElement('small');sub.textContent=item.from;b.append(title,sub);b.addEventListener('click',()=>{selected=i;prepared=false;feedback.textContent='';render()});list.append(b)});sender.textContent=cases[selected].from;incoming.textContent=cases[selected].incoming;draft.value=prepared?cases[selected].draft:'';draft.placeholder='Pulsa «Preparar respuesta» para ver una propuesta.'}render();
document.querySelector('#prepare').addEventListener('click',()=>{prepared=true;draft.value=cases[selected].draft;feedback.textContent='Borrador preparado. Puedes modificarlo aquí.';draft.focus()});document.querySelector('#approve').addEventListener('click',()=>{feedback.textContent=draft.value.trim()?'Borrador revisado en esta demo. No se ha enviado ningún correo.':'Prepara o escribe un borrador antes de revisarlo.'});
